source 'https://supermarket.chef.io'

cookbook 'vim', '~> 2.1.0'
cookbook 'magic_shell', '~> 1.0.0'
cookbook 'docker', '~> 4.12.0'
cookbook 'docker_compose', '~> 0.2.0', git: 'https://github.com/teracyhq-incubator/chef-cookbook-docker_compose.git', tag: 'v0.2.0'
