name             'teracy-dev'
maintainer       'Teracy, Inc.'
maintainer_email 'hoatlevan@gmail.com'
license          'All rights reserved'
description      'Installs/Configures teracy-dev'
version          '0.4.0'
issues_url 'https://github.com/teracyhq/issues'
source_url 'https://github.com/teracyhq/issues'

depends 'magic_shell'
depends 'docker'
